# Generated by Django 5.2.4 on 2025-08-15 10:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunHistory',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(max_length=20)),
                ('source_id', models.UUIDField()),
                ('name', models.CharField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'run_history',
            },
        ),
    ]
