# Generated by Django 5.2.4 on 2025-08-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runhistory',
            name='source_id',
            field=models.CharField(),
        ),
    ]
