# Generated by Django 5.2.4 on 2025-08-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0002_alter_runhistory_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='runhistory',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
