# Generated by Django 5.2.4 on 2026-01-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monitor', '0003_runhistory_user_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='runhistory',
            index=models.Index(fields=['user_id', 'started_at'], name='run_history_user_id_657985_idx'),
        ),
        migrations.AddIndex(
            model_name='runhistory',
            index=models.Index(fields=['user_id', 'source_type', 'status'], name='run_history_user_id_7cdff6_idx'),
        ),
        migrations.AddIndex(
            model_name='runhistory',
            index=models.Index(fields=['started_at'], name='run_history_started_add9da_idx'),
        ),
    ]
