# Generated by Django 5.2.4 on 2025-07-22 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Connections', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='connections',
            table='Connections',
        ),
    ]
