# Generated by Django 5.2.4 on 2025-07-24 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connections', '0003_alter_connections_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnections',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='databaseconnections',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
