# Generated by Django 5.2.4 on 2025-09-18 10:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connections', '0004_databaseconnections_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remote_file_connections',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_column='hostname', max_length=500, null=True)),
                ('username', models.CharField(db_column='username', max_length=500, null=True)),
                ('password', models.CharField(db_column='password', max_length=500, null=True)),
                ('port', models.IntegerField(db_column='port', null=True)),
                ('connection_name', models.CharField(db_column='connection_name', max_length=500, null=True)),
                ('server_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Connections.datasources')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Remote_File_connections',
            },
        ),
    ]
