# Generated by Django 5.2.4 on 2026-01-06 11:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connections', '0005_remote_file_connections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=500)),
                ('site_url', models.CharField(max_length=400)),
                ('credentials', models.JSONField()),
                ('token_metadata', models.JSONField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
