# Generated by Django 5.2.4 on 2026-01-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Connections', '0006_integrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrations',
            old_name='display_name',
            new_name='connection_name',
        ),
        migrations.AlterModelTable(
            name='integrations',
            table='Integrations',
        ),
    ]
