# Generated by Django 5.2.4 on 2026-01-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connections', '0007_rename_display_name_integrations_connection_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrations',
            name='site_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
