# Generated by Django 5.2.10 on 2026-02-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connections', '0008_alter_integrations_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileconnections',
            name='selected_sheets',
            field=models.JSONField(blank=True, default=list, help_text='List of selected sheet names for Excel files', null=True),
        ),
        migrations.AddField(
            model_name='fileconnections',
            name='sheet_relationships',
            field=models.JSONField(blank=True, default=dict, help_text='Parent-child relationships between sheets', null=True),
        ),
    ]
