# Generated by Django 5.2.4 on 2025-10-01 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TaskPlan", "0003_taskplan_scheduled_taskplan_scheduled_id"),
        ("Tasks_Scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskplan",
            name="scheduled_id",
        ),
        migrations.AddField(
            model_name="taskplan",
            name="schedule_id",
            field=models.ForeignKey(
                blank=True,
                db_column="schedule_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Tasks_Scheduler.schedule",
            ),
        ),
    ]
