# Generated by Django 5.2.4 on 2025-07-22 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 4, 23, 30, 646490, tzinfo=datetime.timezone.utc)),
        ),
    ]
