# Generated by Django 5.2.4 on 2025-07-24 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_account_activation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 6, 26, 34, 234370, tzinfo=datetime.timezone.utc)),
        ),
    ]
