# Generated by Django 5.2.4 on 2025-07-31 12:45

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_account_activation_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset_Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(db_column='user_id', null=True)),
                ('key', models.CharField(blank=True, db_column='key', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reset_password',
            },
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 12, 45, 26, 19782, tzinfo=datetime.timezone.utc)),
        ),
    ]
