# Generated by Django 5.2.4 on 2025-07-31 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_reset_password_alter_account_activation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 2, 13, 17, 41, 400671, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='reset_password',
            name='user',
        ),
        migrations.AddField(
            model_name='reset_password',
            name='user',
            field=models.UUIDField(db_column='user_id', null=True),
        ),
    ]
