# Generated by Django 5.2.4 on 2025-08-12 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_account_activation_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 14, 4, 32, 49, 287126, tzinfo=datetime.timezone.utc)),
        ),
    ]
