# Generated by Django 5.2.4 on 2025-08-15 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_account_activation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 17, 10, 55, 43, 759316, tzinfo=datetime.timezone.utc)),
        ),
    ]
