# Generated by Django 5.2.4 on 2025-08-19 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_account_activation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 21, 12, 19, 55, 764192, tzinfo=datetime.timezone.utc)),
        ),
    ]
