# Generated by Django 5.2.4 on 2025-09-18 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_account_activation_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 20, 10, 42, 59, 789183, tzinfo=datetime.timezone.utc)),
        ),
    ]
