# Generated by Django 5.2.4 on 2025-10-01 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_alter_account_activation_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account_activation",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 3, 4, 16, 25, 645278, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
