# Generated by Django 5.2.4 on 2025-10-27 08:57

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_alter_account_activation_expiry_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "permission",
            },
        ),
        migrations.AlterField(
            model_name="account_activation",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 29, 8, 57, 13, 860849, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="authentication.permission"
                    ),
                ),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="authentication.role"
            ),
        ),
    ]
