# Generated by Django 5.2.4 on 2025-10-27 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0014_permission_alter_account_activation_expiry_date_role_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="account_activation",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 29, 9, 4, 29, 370126, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
