# Generated by Django 5.2.4 on 2025-10-27 10:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0016_alter_role_options_permission_module_role_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="account_activation",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 29, 10, 29, 36, 61467, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="account_activation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
