# Generated by Django 5.2.4 on 2025-10-28 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_alter_account_activation_expiry_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account_activation",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 30, 6, 43, 13, 8868, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="userinvite",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 30, 6, 43, 13, 8868, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
