# Generated by Django 5.2.4 on 2025-10-28 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0019_alter_account_activation_expiry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="default",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="account_activation",
            name="expiry_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 30, 7, 28, 58, 156089, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="userinvite",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 30, 7, 28, 58, 156089, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
