# Generated by Django 5.2.4 on 2026-01-06 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_role_default_alter_account_activation_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 8, 11, 6, 4, 606434, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 8, 11, 6, 4, 607430, tzinfo=datetime.timezone.utc)),
        ),
    ]
