# Generated by Django 5.0.7 on 2025-11-11 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_account_activation_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 7, 22, 33, 465958, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 7, 22, 33, 466972, tzinfo=datetime.timezone.utc)),
        ),
    ]
