# Generated by Django 5.0.7 on 2025-11-11 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_alter_account_activation_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 10, 5, 49, 900451, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 10, 5, 49, 902622, tzinfo=datetime.timezone.utc)),
        ),
    ]
