# Generated by Django 5.2.4 on 2026-01-14 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_alter_account_activation_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 16, 49, 22, 559158, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 16, 49, 22, 560607, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(db_column='email_id', db_index=True, max_length=254, unique=True),
        ),
    ]
