# Generated by Django 5.2.4 on 2026-01-26 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_account_activation_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 28, 11, 46, 45, 218517, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 28, 11, 46, 45, 219516, tzinfo=datetime.timezone.utc)),
        ),
    ]
