# Generated by Django 5.2.4 on 2025-07-21 05:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowBoard',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Flow_id', models.CharField()),
                ('Flow_name', models.CharField()),
                ('DrawFlow', models.CharField()),
                ('parsed', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'FlowBoard',
            },
        ),
    ]
