# Generated by Django 5.2.4 on 2025-10-01 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowBoard", "0002_initial"),
        ("Tasks_Scheduler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowboard",
            name="scheduled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flowboard",
            name="scheduled_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                db_column="schedule_id",
                on_delete=django.db.models.deletion.SET_NULL,
                to="Tasks_Scheduler.schedule",
            ),
            preserve_default=False,
        ),
    ]
