# Generated by Django 5.2.4 on 2025-10-01 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowBoard", "0003_flowboard_scheduled_flowboard_scheduled_id"),
        ("Tasks_Scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowboard",
            name="scheduled_id",
        ),
        migrations.AddField(
            model_name="flowboard",
            name="schedule_id",
             field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                db_column="schedule_id",
                on_delete=django.db.models.deletion.SET_NULL,
                to="Tasks_Scheduler.schedule",
            ),
        ),
    ]
