# Generated by Django 5.2.4 on 2025-10-01 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FlowBoard", "0004_remove_flowboard_scheduled_id_flowboard_schedule_id"),
        ("Tasks_Scheduler", "0002_alter_schedule_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowboard",
            name="schedule_id",
            field=models.ForeignKey(
                blank=True,
                db_column="schedule_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Tasks_Scheduler.schedule",
            ),
        ),
    ]
