# Generated by Django 5.2.10 on 2026-03-26 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('connector_type', models.CharField(choices=[('hubspot', 'HubSpot'), ('salesforce', 'Salesforce'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('api', 'REST API')], max_length=50)),
                ('connector_role', models.CharField(choices=[('source', 'Source'), ('destination', 'Destination')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Connection credentials and settings')),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_status', models.CharField(blank=True, max_length=20, null=True)),
                ('test_message', models.TextField(blank=True, null=True)),
                ('user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'datasync_connectors',
                'indexes': [models.Index(fields=['user_id', 'connector_type'], name='datasync_co_user_id_3a4ba2_idx'), models.Index(fields=['is_active'], name='datasync_co_is_acti_f24183_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('destination_schema', models.CharField(default='public', max_length=255)),
                ('table_prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_mode', models.CharField(choices=[('full', 'Full Refresh (Historical)'), ('incremental_timestamp', 'Incremental (Timestamp)'), ('incremental_id', 'Incremental (ID)'), ('incremental_cursor', 'Incremental (Cursor)')], default='full', max_length=50)),
                ('sync_frequency', models.CharField(choices=[('manual', 'Manual'), ('15min', 'Every 15 minutes'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Cron')], default='manual', max_length=20)),
                ('cron_expression', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error'), ('configuring', 'Configuring')], default='configuring', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('dag_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_jobs', to='DataSync.syncconnector')),
                ('source_connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_jobs', to='DataSync.syncconnector')),
            ],
            options={
                'db_table': 'datasync_jobs',
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial_success', 'Partial Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('trigger_type', models.CharField(default='manual', help_text='manual, scheduled, api', max_length=20)),
                ('dag_run_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('tables_synced', models.IntegerField(default=0)),
                ('rows_inserted', models.BigIntegerField(default=0)),
                ('rows_updated', models.BigIntegerField(default=0)),
                ('rows_deleted', models.BigIntegerField(default=0)),
                ('rows_failed', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='DataSync.syncjob')),
            ],
            options={
                'db_table': 'datasync_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_table', models.CharField(help_text='Source table or API object name', max_length=255)),
                ('source_schema', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_table', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sync_mode', models.CharField(blank=True, help_text='Override job sync mode', max_length=50, null=True)),
                ('cursor_field', models.CharField(blank=True, help_text='Field for incremental sync', max_length=255, null=True)),
                ('primary_key_field', models.CharField(blank=True, max_length=255, null=True)),
                ('column_mapping', models.JSONField(default=dict, help_text='Source to destination column mapping')),
                ('source_filter', models.JSONField(blank=True, default=dict, help_text='Filter conditions for source data', null=True)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('last_synced_value', models.CharField(blank=True, help_text='Last cursor value', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='DataSync.syncjob')),
            ],
            options={
                'db_table': 'datasync_tables',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='DataSync.syncrun')),
                ('sync_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataSync.synctable')),
            ],
            options={
                'db_table': 'datasync_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SyncCursor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_value', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('next_page_token', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cursor', to='DataSync.synctable')),
            ],
            options={
                'db_table': 'datasync_cursors',
            },
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['user_id', 'status'], name='datasync_jo_user_id_7bbdc7_idx'),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['status', 'next_sync_at'], name='datasync_jo_status_19132f_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['sync_job', '-created_at'], name='datasync_ru_sync_jo_ee2f26_idx'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['status', '-created_at'], name='datasync_ru_status_49af39_idx'),
        ),
        migrations.AddIndex(
            model_name='synctable',
            index=models.Index(fields=['sync_job', 'is_enabled'], name='datasync_ta_sync_jo_6977b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='synctable',
            unique_together={('sync_job', 'source_table')},
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['sync_run', '-timestamp'], name='datasync_lo_sync_ru_3bbbae_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['level', '-timestamp'], name='datasync_lo_level_9d29c6_idx'),
        ),
    ]
